#!/bin/bash

#~~~~~~~~~~~~~~~
# CONFIGURATION
#~~~~~~~~~~~~~~~
nonroot_username="samedamci"
packages="zsh neovim rsync git curl wget docker-compose"
docker="yes"
arch="amd64" # available: amd64, armhf, arm64

# update
apt-get update && apt-get upgrade -y

# install packages
apt-get install $packages -y

# install Docker
[ "$docker" = "yes" ] && install_docker
install_docker() {
  apt-get install apt-transport-https ca-certificates curl gnupg-agent \
    software-properties-common
  curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  add-apt-repository "deb [arch=$arch] https://download.docker.com/linux/debian \
   $(lsb_release -cs) stable"
  apt-get update
  apt-get install docker-ce docker-ce-cli containerd.io -y
}

# zsh
chsh -s /usr/bin/zsh
chsh -s /usr/bin/zsh "$nonroot_username"
touch /home/$nonroot_username/.zshrc

printf "\n%s" \
  "PROMPT='%F{red}%n%f %F{green}%m%f in %B%F{#299b9b}%~%f%b
%f%F{#777ca5}(%B%F{red}%?%f%b%F{#777ca5})>%b%f '

autoload -U compinit
zstyle ':completion:*' menu select
setopt complete_aliases

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

setopt correct
zmodload zsh/complist
compinit
_comp_options+=(globdots)

bindkey -v
export KEYTIMEOUT=1

function zle-keymap-select {
  if [[ \${KEYMAP} == vicmd ]] ||
    [[ \$1 = 'block' ]]; then
      echo -ne '\e[2 q'
    elif [[ \${KEYMAP} == main ]] ||
      [[ \${KEYMAP} == viins ]] ||
      [[ \${KEYMAP} = '' ]] ||
      [[ \$1 = 'beam' ]]; then
	echo -ne '\e[6 q'
  fi
}

zle -N zle-keymap-select

zle-line-init() {
    echo -ne \"\e[6 q\"
}

echo -ne '\e[6 q'
preexec() { echo -ne '\e[6 q' ;}" >> /etc/zsh/zshrc

# aliases


# nvim


# ssh
